import { useEffect, useState } from "react";
import { useParams, useNavigate } from "react-router-dom";
import { getLabBillById } from "../../../api/api";
import "../Add.css";

const ViewBill = () => {
    const { id } = useParams();
    const navigate = useNavigate();

    const [bill, setBill] = useState(null);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        const fetchBill = async () => {
            try {
                const res = await getLabBillById(id);
                setBill(res.data);
            } catch (err) {
                console.error("Error fetching bill:", err);
                alert("Failed to fetch bill details");
            } finally {
                setLoading(false);
            }
        };
        fetchBill();
    }, [id]);

    if (loading) return <div className="loading-state">Loading bill details...</div>;
    if (!bill) return <div className="error-state">Bill not found</div>;

    const formatDate = (dateString) => {
        if (!dateString) return "N/A";
        return new Date(dateString).toLocaleDateString('en-IN', {
            day: '2-digit',
            month: 'short',
            year: 'numeric'
        });
    };

    const formatAmount = (amount) => {
        return new Intl.NumberFormat('en-IN', {
            style: 'currency',
            currency: 'INR',
            minimumFractionDigits: 2
        }).format(amount || 0);
    };

    return (
        <div className="view-container">
            <div className="view-card">
                <div className="view-header">
                    <div className="view-title">
                        <h1>Lab Bill Details</h1>
                        <p className="subtitle">Complete bill information and items</p>
                    </div>
                    <div className="bill-id">
                        <span className="bill-id-number">#{bill.LabBill_id}</span>
                        <span className={`status-badge ${bill.payment_status === 'paid' ? 'status-paid' : 'status-pending'}`}>
                            {bill.payment_status === 'paid' ? 'Paid' : 'Pending'}
                        </span>
                    </div>
                </div>

                <div className="bill-summary">
                    <div className="summary-info">
                        <div className="info-group">
                            <label>Patient</label>
                            <div className="info-value patient-name">
                                {bill.patient_name || `Patient ID: ${bill.patient}`}
                            </div>
                        </div>
                        <div className="info-group">
                            <label>Bill Date</label>
                            <div className="info-value bill-date">
                                {formatDate(bill.bill_date)}
                            </div>
                        </div>
                        <div className="info-group">
                            <label>Generated By</label>
                            <div className="info-value">
                                {bill.generated_by || "System"}
                            </div>
                        </div>
                    </div>
                    <div className="total-amount">
                        <div className="total-label">Total Amount</div>
                        <div className="total-value">{formatAmount(bill.total_amount)}</div>
                    </div>
                </div>

                <div className="bill-items-section">
                    <h3>Bill Items</h3>
                    <div className="table-wrapper">
                        <table className="bill-items-table">
                            <thead>
                                <tr>
                                    <th>ITEM</th>
                                    <th>DESCRIPTION</th>
                                    <th>PRICE</th>
                                    <th>SUBTOTAL</th>
                                </tr>
                            </thead>
                            <tbody>
                                {bill.items && bill.items.length > 0 ? (
                                    bill.items.map((item, index) => (
                                        <tr key={item.LabBillItem_id || index}>
                                            <td className="item-name">
                                                {item.test_name || item.test?.category_name || "N/A"}
                                            </td>
                                            <td className="item-desc">
                                                {item.description || "Lab Test"}
                                            </td>
                                            <td className="item-price">
                                                {formatAmount(item.price)}
                                            </td>
                                            <td className="item-subtotal">
                                                {formatAmount(item.subtotal)}
                                            </td>
                                        </tr>
                                    ))
                                ) : (
                                    <tr>
                                        <td colSpan="4" className="text-center">
                                            No items found
                                        </td>
                                    </tr>
                                )}
                            </tbody>
                            <tfoot>
                                <tr className="bill-total">
                                    <td colSpan="3" className="total-label-cell">
                                        <strong>Total Amount</strong>
                                    </td>
                                    <td className="total-amount-cell">
                                        <strong>{formatAmount(bill.total_amount)}</strong>
                                    </td>
                                </tr>
                                {bill.discount > 0 && (
                                    <tr className="bill-discount">
                                        <td colSpan="3" className="discount-label-cell">
                                            <strong>Discount</strong>
                                        </td>
                                        <td className="discount-amount-cell">
                                            <strong>-{formatAmount(bill.discount)}</strong>
                                        </td>
                                    </tr>
                                )}
                                <tr className="bill-grand-total">
                                    <td colSpan="3" className="grand-total-label-cell">
                                        <strong>Grand Total</strong>
                                    </td>
                                    <td className="grand-total-amount-cell">
                                        <strong>{formatAmount(bill.total_amount - (bill.discount || 0))}</strong>
                                    </td>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>

                <div className="bill-actions">
                    <button 
                        className="btn-secondary" 
                        onClick={() => navigate("/lab-bills")}
                    >
                        ← Back to Bills
                    </button>
                    <div className="action-buttons">
                        <button 
                            className="btn-print"
                            onClick={() => window.print()}
                        >
                            🖨️ Print Bill
                        </button>
                        <button 
                            className="btn-pdf"
                            onClick={() => alert("PDF generation coming soon!")}
                        >
                            📄 Download PDF
                        </button>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default ViewBill;